### ISSUE TITLE
Ability to check list of proxies and save the working proxies in txt file

### ISSUE THREAD

**Issue by bawzz234** [askanton71/ProxyChecker#1]
Hello, 

Great proxy checker for checking single proxy. Would be great if you can also check the proxies in a list (example: proxies.txt) and save the working proxies in a txt file. 

Looking forward to hear from you.

Best Regards

**Comment by askanton71** [comment]
Now you can use **ProxyChecker2.0** https://github.com/askanton71/ProxyChecker/blob/master/proxyChecker_gui/file_checker_gui.py

**Comment by bawzz234** [comment]
Great work on adding file checking option. It is working properly and checking is very accurate. 

It would be great if you could also add threads to it so it will check faster. 

Also if possible, set the ability to use the file_checker without the gui as well. for example, using the following features: 

file_checker.py -threads 500 -timeout 3 -type socks5,socks4,https (or single type) -type socks4 -input test.txt -output hits.txt -url https://www.google.com/humans.txt -intext engineers 

if multiple -type is selected then the output will be generated by the type whenever it finds a working proxy and add to the list. 

For example, -type socks4,socks5 selected and the program found working proxies from bot types, then it will save them in socks4.txt and socks5.txt

  - these features will be a great additions to your program. 

Best Regards
