### ISSUE TITLE
File_checker needs a multi-threading

### ISSUE THREAD

**Issue by bawzz234** [askanton71/ProxyChecker#2]
Great work on adding file checking option. It is working properly and checking is very accurate.

It would be great if you could also add threads to it so it will check faster.

Also if possible, set the ability to use the file_checker without the gui as well. for example, using the following features:

file_checker.py -threads 500 -timeout 3 -type socks5,socks4,https (or single type) -type socks4 -input test.txt -output hits.txt -url https://www.google.com/humans.txt -intext engineers

if multiple -type is selected then the output will be generated by the type whenever it finds a working proxy and add to the list.

For example, -type socks4,socks5 selected and the program found working proxies from bot types, then it will save them in socks4.txt and socks5.txt

these features will be a great additions to your program.

Best Regards

**Comment by askanton71** [comment]
Threads added)

**Comment by bawzz234** [comment]
Hello,

Just tested, threading is working wonderfully! thanks for adding this feature. 

The other features I have mentioned aren't much needed because they are already implanted in GUI. Though, a custom URL option will be useful. 

Best Regards
